# Generated by Django 2.2 on 2019-04-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190417_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnum',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
