# Generated by Django 2.2 on 2019-04-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190417_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
